ğŸ“Š metrics embed:
  - source/app/action/**
  - source/app/web/**
âœ¨ metrics insights:
  - source/app/web/statics/about/**

ğŸ§© plugins:
  - source/plugins/**
ğŸ–¼ï¸ templates:
  - source/templates/**

ğŸ—ƒï¸ base:
  - source/plugins/base/**
ğŸ§± core:
  - source/app/metrics/**
  - source/plugins/core/**

ğŸ² community plugin:
  - source/plugins/community/**

ğŸ† plugin achievements:
  - source/plugins/achievements/**
ğŸ“° plugin activity:
  - source/plugins/activity/**
ğŸŒ¸ plugin anilist:
  - source/plugins/anilist/**
ğŸ“† plugin calendar:
  - source/plugins/calendar/**
â™ plugin code:
  - source/plugins/code/**
ğŸ… plugin contributors:
  - source/plugins/contributors/**
ğŸ’¬ plugin discussions:
  - source/plugins/discussions/**
ğŸŸï¸ plugin followup:
  - source/plugins/followup/**
ğŸ« plugin gists:
  - source/plugins/gists/**
ğŸ’¡ plugin habits:
  - source/plugins/habits/**
ğŸ™‹ plugin introduction:
  - source/plugins/introduction/**
ğŸ“… plugin isocalendar:
  - source/plugins/isocalendar/**
ğŸˆ·ï¸ plugin languages:
  - source/plugins/languages/**
ğŸ“œ plugin licenses:
  - source/plugins/licenses/**
ğŸ‘¨â€ğŸ’» plugin lines:
  - source/plugins/lines/**
ğŸ¼ plugin music:
  - source/plugins/music/**
ğŸ© plugin notable:
  - source/plugins/notable/**
â±ï¸ plugin pagespeed:
  - source/plugins/pagespeed/**
ğŸ§‘â€ğŸ¤â€ğŸ§‘ plugin people:
  - source/plugins/people/**
âœ’ï¸ plugin posts:
  - source/plugins/posts/**
ğŸ—‚ï¸ plugin projects:
  - source/plugins/projects/**
ğŸ­ plugin reactions:
  - source/plugins/reactions/**
ğŸ““ plugin repositories:
  - source/plugins/repositories/**
ğŸ—¼ plugin rss:
  - source/plugins/rss/**
ğŸŒ‡ plugin skyline:
  - source/plugins/skyline/**
ğŸ’• plugin sponsors:
  - source/plugins/sponsors/**
ğŸ—¨ï¸ plugin stackoverflow:
  - source/plugins/stackoverflow/**
âœ¨ plugin stargazers:
  - source/plugins/stargazers/**
ğŸ’« plugin starlists:
  - source/plugins/starlists/**
ğŸŒŸ plugin stars:
  - source/plugins/stars/**
ğŸ’­ plugin support:
  - source/plugins/support/**
ğŸ“Œ plugin topics:
  - source/plugins/topics/**
ğŸ§® plugin traffic:
  - source/plugins/traffic/**
ğŸ¤ plugin tweets:
  - source/plugins/tweets/**
â° plugin wakatime:
  - source/plugins/wakatime/**