ğŸ“Š metrics embed:
  - source/app/action/**
  - source/app/web/**
âœ¨ metrics insights:
  - source/app/web/statics/about/**

ğŸ§© plugins:
  - source/plugins/**
ğŸ–¼ï¸ templates:
  - source/templates/**

ğŸ—ƒï¸ base:
  - source/plugins/base/**
ğŸ§± core:
  - source/app/metrics/**
  - source/plugins/core/**

ğŸ† plugin achievements:
  - source/plugins/isocalendar/**
ğŸ“° plugin activity:
  - source/plugins/activity/**
â™ plugin code:
  - source/plugins/code/**
ğŸ… plugin contributors:
  - source/plugins/contributors/**
ğŸ’¬ plugin discussions:
  - source/plugins/discussions/**
ğŸŸï¸ plugin followup:
  - source/plugins/followup/**
ğŸ« plugin gists:
  - source/plugins/gists/**
ğŸ’¡ plugin habits:
  - source/plugins/habits/**
ğŸ™‹ plugin introduction:
  - source/plugins/introduction/**
ğŸ“… plugin isocalendar:
  - source/plugins/isocalendar/**
ğŸˆ·ï¸ plugin languages:
  - source/plugins/languages/**
ğŸ“œ plugin licenses:
  - source/plugins/licenses/**
ğŸ‘¨â€ğŸ’» plugin lines:
  - source/plugins/lines/**
ğŸ© plugin notable:
  - source/plugins/notable/**
ğŸ§‘â€ğŸ¤â€ğŸ§‘ plugin people:
  - source/plugins/people/**
ğŸ—‚ï¸ plugin projects:
  - source/plugins/projects/**
ğŸ­ plugin reactions:
  - source/plugins/reactions/**
ğŸ““ plugin repositories:
  - source/plugins/repositories/**
ğŸŒ‡ plugin skyline:
  - source/plugins/skyline/**
ğŸ’• plugin sponsors:
  - source/plugins/sponsors/**
âœ¨ plugin stargazers:
  - source/plugins/stargazers/**
ğŸŒŸ plugin starred:
  - source/plugins/starred/**
ğŸ’­ plugin community:
  - source/plugins/community/**
ğŸ“Œ plugin topics:
  - source/plugins/topics/**
ğŸ§® plugin traffic:
  - source/plugins/traffic/**
ğŸŒ¸ plugin anilist:
  - source/plugins/anilist/**
ğŸ¼ plugin music:
  - source/plugins/music/**
â±ï¸ plugin pagespeed:
  - source/plugins/pagespeed/**
âœ’ï¸ plugin posts:
  - source/plugins/posts/**
ğŸ—¼ plugin rss:
  - source/plugins/rss/**
ğŸ—¨ï¸ plugin stackoverflow:
  - source/plugins/stackoverflow/**
ğŸ¤ plugin tweets:
  - source/plugins/tweets/**
â° plugin wakatime:
  - source/plugins/wakatime/**
ğŸ’‰ plugin nightscout:
  - source/plugins/nightscout/**
ğŸ“¸ plugin screenshot:
  - source/plugins/screenshot/**
ğŸ’¹ plugin stock:
  - source/plugins/stock/**
