blank_issues_enabled: false
contact_links:
  - name: ğŸ™ Request help with setup or report a possible issue
    url: https://github.com/lowlighter/metrics/discussions/new?category=q-a
    about: Post here when having trouble with setup or configuration
  - name: ğŸ’¡ Suggest new features
    url: https://github.com/lowlighter/metrics/discussions/new?category=ideas
    about: Submit ideas to help us improve
  - name: ğŸ’¬ Start a discussion
    url: https://github.com/lowlighter/metrics/discussions/new?category=general
    about: Ask other questions related to this project here