name: Metrics
on:
  push:
    branches:
      - v4-dev
  #pull_request:
  #  branches:
  #    - v4-dev
  #  paths-ignore:
  #    - "**/*.md"
jobs:
  # Lint, format, build and test
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - ci:lint
          - ci:test
    fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno task make ${{ matrix.task }}

  # GitHub CodeQL analysis
  analyze:
    runs-on: ubuntu-latest
    needs:
      - testing
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language:
          - typescript
    steps:
    - uses: actions/checkout@v4
    - uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config: |
          queries:
            - uses: security-and-quality
          paths-ignore:
            - source/run/serve/imported.ts
    - uses: github/codeql-action/analyze@v2

  # Build and push Docker image
  docker:
    if: github.ref == 'refs/heads/v4-dev'
    runs-on: ubuntu-latest
    needs:
      - analyze
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          tags: ghcr.io/${{ github.repository }}:v4
          push: ${{ github.event_name == 'push' }}

  # Test GitHub Action
  github-action:
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - uses: lowlighter/metrics@v4-dev
