name: Stale issue and pull requests

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  stale:
    name: Flag stale issues and pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: This pull request seems to be inactive and will be automatically closed in a few days if it remains without any activity.
          days-before-pr-stale: 21
          days-before-pr-close: 3
          stale-pr-label: ⏹️ stale
          remove-stale-when-updated: yes
          operations-per-run: 100
  lock:
    name: Lock inactive closed issues and pull requests
    needs:
      - stale
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v2
        with:
          github-token: ${{ github.token }}
          issue-lock-inactive-days: 14
          issue-lock-reason: ""
          issue-lock-labels: ☑️ archived
          pr-lock-inactive-days: 14
          pr-lock-reason: ""
          pr-lock-labels: ☑️ archived
